name: Run tests

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python {{ "${{" }} matrix.python-version {{ "}}" }}
      uses: actions/setup-python@v5
      with:
        python-version: {{ "${{" }} matrix.python-version {{ "}}" }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest
{%- if cookiecutter.use_ruff_format %}

    - name: Check format with ruff
      run: |
        ruff format --check
{%- endif %}
{%- if cookiecutter.use_ruff_lint %}

    - name: Check code linting with ruff
      run: |
        ruff check
{%- endif %}
{%- if cookiecutter.use_pytest %}

    - name: Test with pytest
      run: |
        pytest -v
{%- endif %}
