repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args: ["--maxkb=2000"]
  - id: check-case-conflict
  - id: check-illegal-windows-names
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
{%- if cookiecutter.use_ruff_format or cookiecutter.use_ruff_lint %}
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v{{ cookiecutter.__ruff_version }}
  hooks:
{%- if cookiecutter.use_ruff_lint %}
    - id: ruff-check
      args: [ --fix ]
{%- endif %}
{%- if cookiecutter.use_ruff_format %}
    - id: ruff-format
{%- endif %}
{%- endif %}
{%- if cookiecutter.use_uv %}
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: {{ cookiecutter.__uv_version }}
  hooks:
    - id: uv-lock
    - id: uv-export
{%- else %}
- repo: local
  hooks:
  - id: uv-pip-compile
    name: uv pip compile
    entry: uv pip compile pyproject.toml --group dev --universal --output-file requirements.txt --quiet --no-progress
    language: python
    additional_dependencies:
    - uv=={{ cookiecutter.__uv_version }}
    pass_filenames: false
    files: ^pyproject\.toml$
{%- endif %}
